- name: setup  frontend
  hosts: frontend
  become: yes
  tasks:
  - name: disable nginx
    ansible.builtin.command: dnf module disable nginx 

  - name: enable nginx
    ansible.builtin.command: dnf module enable nginx1.24

  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: Remove defaukt html content
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: absent

  - name: create html directory
    ansible.builtin.file:
      state: directory
      path: /usr/share/nginx/html/

  - name: download frontend application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: extract frontend  application
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html 
      remote_src: yes

  - name: remove defaukt content in nginx.configuration
    ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      state: absent

  - name: copy nginx.conf file
    ansible.builitin.copy:
     src: nginx.conf
     dest: /etc/nginx/nginx.conf
  
  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted # restarted if you have already started earlier
      enabled: yes
