[mongodb]
mongodb.daws88s.fun
[redis]
redis.daws88s.fun
[rabbitmq]
rabbitmq.daws88s.fun
[mysql]
mysql.daws88s.fun
[local]
localhost
[local:vars]
ansible_user=ec2-ansible_user
ansible_password=DevOps321
